name: stacked_page_view
description: A flutter plugin to help create a vertical caraousel. This package is very lightweight as the actual code iteself is like 109 lines
version: 1.1.1
homepage: https://github.com/100lvlmaster/stacked_page_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
